name: Run Script on PR Merge

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    # Verifica che la PR sia stata mergiata
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install Salesforce CLI
        run: |
          echo "ðŸ“¦ Installing Salesforce CLI..."
          npm install -g @salesforce/cli
          sf --version

      - name: Configure git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Deploy
        run: |
          echo "Esecuzione script per PR #${{ github.event.pull_request.number }}"
          echo "Source: ${{ github.head_ref }} -> Destination: ${{ github.base_ref }}"
          chmod +x ./release2.0.sh
          ./release2.0.sh deploy ${{ github.head_ref }} ${{ github.base_ref }} true

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployedPackage
          path: ./Release
