name: Run Script on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:      
      - name: script
        run: |
          echo "Esecuzione script per PR #${{ github.event.pull_request.number }}"
          echo "Source: ${{ github.head_ref }} -> Destination: ${{ github.base_ref }}"
          echo "Script completato con successo"
          ls
          chmod +x ./release2.0.sh
          ./release2.0.sh validate PROD ${{ github.head_ref }} ${{ github.base_ref }} true
