name: Run Script on PR

permissions:
  contents: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:      
       - name: Checkout
         uses: actions/checkout@v4
         with:
          fetch-depth: 0
          persist-credentials: true
          # Usa il token di default di GitHub (ha permessi per push tag)

       - name: Install Salesforce CLI
         run: |
           echo "ðŸ“¦ Installing Salesforce CLI..."
           npm install -g @salesforce/cli
           sf --version

       - name: Configure git identity
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
       - name: Validation
         run: |
           echo "Esecuzione script per PR #${{ github.event.pull_request.number }}"
           echo "Source: ${{ github.head_ref }} -> Destination: ${{ github.base_ref }}"
           echo "Script completato con successo"
           ls
           chmod +x ./release2.0.sh
           ./release2.0.sh validate ${{ github.head_ref }} ${{ github.base_ref }} true
       
       - name: Set up Java
         uses: actions/setup-java@v3
         with:
          distribution: temurin
          java-version: '17'

      # --- Download PMD ---
       - name: Download PMD
         run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.64.0/pmd-bin-6.64.0.zip
          unzip pmd-bin-6.64.0.zip
          echo "$PWD/pmd-bin-6.64.0/bin" >> $GITHUB_PATH

      # --- Run PMD analysis ---
       - name: Run PMD on Apex
         run: |
          mkdir -p ./Release/pmd
          pmd -d ./Release/force-app/main/default/classes -R rulesets/apex/quickstart.xml -f html -r ./Release/pmd/pmd-report.html || true

      # --- Upload PMD report as artifact ---
       - name: Upload PMD report
         uses: actions/upload-artifact@v3
         with:
          name: PMD-report
          path: ./Release/pmd/pmd-report.html

      # --- Fail on PMD violations ---
       - name: Fail if PMD violations
         run: |
          if grep -q "<violation" ./Release/pmd/pmd-report.html; then
            echo "PMD violations found. See report in artifacts."
            exit 1
          else
            echo "No PMD violations"
          fi
          
       - name: Upload artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: validationPackage
           path: ./Release
