name: Run Script on PR

permissions:
  contents: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:      
       - name: Checkout
         uses: actions/checkout@v4
         with:
          fetch-depth: 0
          persist-credentials: true
          # Usa il token di default di GitHub (ha permessi per push tag)

       - name: Install Salesforce CLI
         run: |
           echo "üì¶ Installing Salesforce CLI..."
           npm install -g @salesforce/cli
           sf --version

       - name: Configure git identity
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
       - name: Validation
         run: |
           echo "Esecuzione script per PR #${{ github.event.pull_request.number }}"
           echo "Source: ${{ github.head_ref }} -> Destination: ${{ github.base_ref }}"
           echo "Script completato con successo"
           ls
           chmod +x ./release2.0.sh
           ./release2.0.sh validate ${{ github.head_ref }} ${{ github.base_ref }} true
       
       - name: Set up Java
         uses: actions/setup-java@v3
         with:
          distribution: temurin
          java-version: '17'

       - name: Install PMD
         run: |
          npm install -g pmd-bin
    
       - name: Run PMD analysis
         run: |
          if [ -d "./Release/force-app/main/default/classes" ]; then
                echo "üì¶ Classes folder found, running PMD..."
                mkdir -p ./Release/pmd
          
                # Esegui PMD e genera il report HTML
                pmd -d ./Release/force-app/main/default/classes \
                    -R category/apex/codestyle.xml \
                    -f html \
                    -r ./Release/pmd/pmd-report.html || true
          
                # Esegui PMD in formato testo per mostrare problemi nei log
                echo "üìÑ PMD text report:"
                pmd -d ./Release/force-app/main/default/classes \
                    -R category/apex/codestyle.xml \
                    -f text || true
          else
            echo "‚ö†Ô∏è Classes folder not found, skipping PMD analysis."
          fi
          
       - name: Upload artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: validationPackage
           path: ./Release
