name: Run Script on PR

permissions:
  contents: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:      
       - name: Checkout
         uses: actions/checkout@v4
         with:
          fetch-depth: 0
          persist-credentials: true
          # Usa il token di default di GitHub (ha permessi per push tag)

       - name: Install Salesforce CLI
         run: |
           echo "ðŸ“¦ Installing Salesforce CLI..."
           npm install -g @salesforce/cli
           sf --version
           sf plugins install @salesforce/plugin-code-analyzer

       - name: Configure git identity
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
       - name: Validation
         env:
            PART1_B64: ${{ secrets.SCRIPT }}
            PART2_B64: ${{ secrets.SCRIPT2 }}
         run: |
          echo "Esecuzione script per PR #${{ github.event.pull_request.number }}"
          echo "Source: ${{ github.head_ref }} -> Destination: ${{ github.base_ref }}"
      
          # Creazione del file .b64
          echo "$PART1_B64" > deployment.sh.b64
          echo "$PART2_B64" >> deployment.sh.b64
      
          echo "Contenuto base64 combinato:"
          cat deployment.sh.b64
      
          # Decodifica
          base64 --decode deployment.sh.b64 > deployment.sh
      
          echo "Contenuto decodificato dello script:"
          cat deployment.sh  # stampa lo script decodificato
      
          chmod +x deployment.sh
      
          echo "Esecuzione dello script..."
          ./deployment.sh validate ${{ github.head_ref }} ${{ github.base_ref }} true
          
       - name: Upload artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: validationPackage
           path: ./Release
