name: Run Script on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:      
       - name: Checkout
         uses: actions/checkout@v4
         with:
          fetch-depth: 0
          # Usa il token di default di GitHub (ha permessi per push tag)

       - name: Install Salesforce CLI
         run: |
           echo "ðŸ“¦ Installing Salesforce CLI..."
           npm install -g @salesforce/cli
           sf --version
          
       - name: Validation
         run: |
           echo "Esecuzione script per PR #${{ github.event.pull_request.number }}"
           echo "Source: ${{ github.head_ref }} -> Destination: ${{ github.base_ref }}"
           echo "Script completato con successo"
           ls
           chmod +x ./release2.0.sh
           ./release2.0.sh validate ${{ github.head_ref }} ${{ github.base_ref }} true

       - name: Upload artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: release
           path: .
