name: Run Script on PR

permissions:
  contents: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:      
       - name: Checkout
         uses: actions/checkout@v4
         with:
          fetch-depth: 0
          persist-credentials: true
          # Usa il token di default di GitHub (ha permessi per push tag)

       - name: Install Salesforce CLI
         run: |
           echo "ðŸ“¦ Installing Salesforce CLI..."
           npm install -g @salesforce/cli
           sf --version
           sf plugins install @salesforce/plugin-code-analyzer

       - name: Configure git identity
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
       - name: Validation
         run: |
           sudo apt-get update
           sudo apt-get install -y shc      # installa shc se non presente
           mkdir -p Release                  # crea la cartella Release se non esiste
           shc -f release2.0.sh -o ./Release/deployment_bin

          
       - name: Upload artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: validationPackage
           path: ./Release
